### ISSUE TITLE
compared to acemtp

### ISSUE THREAD

**Issue by KristerV** [poetic/accounts-passwordless#1]
hey, how is this different from [acemtp:accounts-passwordless](https://github.com/acemtp/meteor-accounts-passwordless)?

**Comment by JohnRodney** [comment]
This offered a few different solutions we needed.  It works through email routing a link that will permanently auth a user, and it also has another addition which supports SMS phone authorization which we are still testing and have not yet released to atmosphere.

**Comment by KristerV** [comment]
ok.
